//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystemManagement2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class advisor
    {
        public string s_ID { get; set; }
        public string i_ID { get; set; }
    
        public virtual instructor instructor { get; set; }
        public virtual student student { get; set; }
    }
}
