//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystemManagement2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class classroom
    {
        public classroom()
        {
            this.sections = new HashSet<section>();
        }
    
        public string building { get; set; }
        public string room_number { get; set; }
        public Nullable<decimal> capacity { get; set; }
    
        public virtual ICollection<section> sections { get; set; }
    }
}
