//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystemManagement2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class course
    {
        public course()
        {
            this.sections = new HashSet<section>();
            this.course1 = new HashSet<course>();
            this.courses = new HashSet<course>();
        }
    
        public string course_id { get; set; }
        public string title { get; set; }
        public string dept_name { get; set; }
        public Nullable<decimal> credits { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<section> sections { get; set; }
        public virtual ICollection<course> course1 { get; set; }
        public virtual ICollection<course> courses { get; set; }
    }
}
