//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystemManagement2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructor
    {
        public instructor()
        {
            this.advisors = new HashSet<advisor>();
            this.sections = new HashSet<section>();
        }
    
        public string ID { get; set; }
        public string name { get; set; }
        public string dept_name { get; set; }
        public Nullable<decimal> salary { get; set; }
    
        public virtual ICollection<advisor> advisors { get; set; }
        public virtual department department { get; set; }
        public virtual ICollection<section> sections { get; set; }
    }
}
