//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySystemManagement2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_slot
    {
        public string time_slot_id { get; set; }
        public string day { get; set; }
        public decimal start_hr { get; set; }
        public decimal start_min { get; set; }
        public Nullable<decimal> end_hr { get; set; }
        public Nullable<decimal> end_min { get; set; }
    }
}
