//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management_System_2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.courses = new HashSet<course>();
            this.instructors = new HashSet<instructor>();
            this.students = new HashSet<student>();
        }
    
        public string dept_name { get; set; }
        public string building { get; set; }
        public Nullable<decimal> budget { get; set; }
    
        public virtual ICollection<course> courses { get; set; }
        public virtual ICollection<instructor> instructors { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}
