//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management_System_2026
{
    using System;
    using System.Collections.Generic;
    
    public partial class take
    {
        public string ID { get; set; }
        public string course_id { get; set; }
        public string sec_id { get; set; }
        public string semester { get; set; }
        public decimal year { get; set; }
        public string grade { get; set; }
    
        public virtual section section { get; set; }
        public virtual student student { get; set; }
    }
}
