//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University_Management_System_2026
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<advisor> advisors { get; set; }
        public DbSet<classroom> classrooms { get; set; }
        public DbSet<course> courses { get; set; }
        public DbSet<department> departments { get; set; }
        public DbSet<instructor> instructors { get; set; }
        public DbSet<section> sections { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<take> takes { get; set; }
        public DbSet<time_slot> time_slot { get; set; }
        public DbSet<user> users { get; set; }
    }
}
